/**
 * AUDIT THE DATA BEFORE TRUSTING ANY MODEL FITTED ON IT.
 *
 * Every model report in this repository quotes four decimal places. None of
 * them, until now, checked whether the rows underneath are what they claim to
 * be. That gap has already cost this project once: `validate-variables.ts`
 * produced ZERO player-seasons out of eight seasons of real data, wrote a report
 * concluding nothing was significant, and looked exactly like a clean run
 * (`src/lib/stats/csv.ts` was extracted afterwards).
 *
 * So this runs first and answers, for both datasets the models use:
 *
 *   1. HOW MANY ROWS, and across which seasons, weeks and positions. A count is
 *      the cheapest possible check and it catches the whole class of parser
 *      failures that silently drop most of the input.
 *   2. ARE THE KEYS UNIQUE. Duplicate (player, season, week) rows would be
 *      double-counted by every aggregate and would quietly inflate any
 *      per-player history feature.
 *   3. MISSINGNESS, per column the models actually read — not overall. A column
 *      that is 90% empty is unusable regardless of how good its correlation
 *      looks on the 10%.
 *   4. IS THE OUTCOME COLUMN CORRECT. `fantasy_points_ppr` is the target for
 *      every holdout model, and it is taken on faith. It is recomputed here from
 *      its own components under standard PPR scoring and compared row by row. If
 *      those disagree, either the scoring assumption is wrong or the column is,
 *      and both invalidate everything downstream.
 *   5. BASE RATES against the shipped thresholds, per position. A threshold that
 *      almost nobody clears, or almost everybody, makes a probability model
 *      pointless before it is fitted — and the number is worth knowing rather
 *      than assuming.
 *
 * Findings are printed AND written to a report. A data audit whose output scrolls
 * off a terminal is not evidence.
 *
 *   npx tsx scripts/audit-model-data.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { parseCsvRows } from "../src/lib/stats/csv";
import { WEEKLY_PROB_MODELS, type WeeklyPosition } from "../src/lib/models/weeklyProbability";

const NFLVERSE = "reports/2026-08-20/nflverse-usage.json.gz";
const WEEKLY_2025 = "reports/2026-08-20/brier-prospective.json.gz";
const OUT = "docs/model-data-audit.md";
const POSITIONS: WeeklyPosition[] = ["QB", "RB", "WR", "TE"];

/** Columns the holdout models read. Missingness is reported per column, here. */
const USED_COLUMNS = [
  "player_id",
  "position",
  "season",
  "week",
  "season_type",
  "fantasy_points_ppr",
  "targets",
  "receptions",
  "carries",
  "target_share",
  "air_yards_share",
  "wopr",
  "receiving_yards",
  "rushing_yards"
] as const;

const num = (v: string | undefined): number | null => {
  if (v === undefined || v === "" || v === "NA") return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
};

/**
 * Standard PPR from components, for cross-checking `fantasy_points_ppr`.
 *
 * Deliberately written out rather than imported: the point is an INDEPENDENT
 * recomputation. Reusing whatever produced the column would compare it to
 * itself.
 */
function recomputePpr(r: Record<string, string>): number {
  const g = (k: string) => num(r[k]) ?? 0;
  return (
    g("passing_yards") / 25 +
    g("passing_tds") * 4 +
    g("interceptions") * -2 +
    g("rushing_yards") / 10 +
    g("rushing_tds") * 6 +
    g("receiving_yards") / 10 +
    g("receiving_tds") * 6 +
    g("receptions") * 1 +
    // Return touchdowns. Omitting these produced 97 rows off by EXACTLY 6.0 or
    // 12.0 — one or two scores — on the first run of this audit. The defect was
    // in this function, not in the data, which is the outcome an audit should be
    // equally willing to reach.
    g("special_teams_tds") * 6 +
    (g("passing_2pt_conversions") + g("rushing_2pt_conversions") + g("receiving_2pt_conversions")) * 2 +
    (g("sack_fumbles_lost") + g("rushing_fumbles_lost") + g("receiving_fumbles_lost")) * -2
  );
}

interface SeasonAudit {
  season: number;
  rows: number;
  malformed: number;
  regRows: number;
  weeks: number;
  duplicates: number;
  pprMismatches: number;
  worstPprDelta: number;
}

function main(): void {
  const lines: string[] = [];
  const bundle = JSON.parse(gunzipSync(readFileSync(NFLVERSE)).toString("utf8")) as Record<string, string>;
  const seasonKeys = Object.keys(bundle)
    .filter((k) => k.startsWith("player_stats_"))
    .sort();

  lines.push("# Model data audit\n");
  lines.push(`**Executed** ${new Date().toISOString()}  \n`);
  lines.push(
    "\n> Generated by `npm run audit:model-data`. Run before trusting any model " +
      "fitted on these rows. Every number below is measured, not assumed.\n"
  );

  // ── 1. nflverse weekly ──────────────────────────────────────────────────
  const audits: SeasonAudit[] = [];
  const missing: Record<string, number> = {};
  let totalConsidered = 0;
  const posCounts: Record<string, number> = {};

  for (const key of seasonKeys) {
    const season = Number(key.replace("player_stats_", ""));
    const parsed = parseCsvRows(bundle[key]!);
    const reg = parsed.rows.filter((r) => r.season_type === "REG");
    const seen = new Set<string>();
    let duplicates = 0;
    let pprMismatches = 0;
    let worst = 0;

    for (const r of reg) {
      const k = `${r.player_id}|${r.week}`;
      if (seen.has(k)) duplicates += 1;
      seen.add(k);

      if (POSITIONS.includes(r.position as WeeklyPosition)) {
        totalConsidered += 1;
        posCounts[r.position!] = (posCounts[r.position!] ?? 0) + 1;
        for (const c of USED_COLUMNS) {
          if (num(r[c]) === null && r[c] !== "REG" && (r[c] ?? "") === "") {
            missing[c] = (missing[c] ?? 0) + 1;
          }
        }
        const declared = num(r.fantasy_points_ppr);
        if (declared !== null) {
          const delta = Math.abs(declared - recomputePpr(r));
          // 0.01 rather than exact: the source stores one decimal place, so a
          // rounding difference is expected and a real disagreement is not.
          if (delta > 0.011) pprMismatches += 1;
          worst = Math.max(worst, delta);
        }
      }
    }

    audits.push({
      season,
      rows: parsed.rows.length,
      malformed: parsed.malformed,
      regRows: reg.length,
      weeks: new Set(reg.map((r) => r.week)).size,
      duplicates,
      pprMismatches,
      worstPprDelta: worst
    });
  }

  lines.push("\n## 1. nflverse weekly player stats\n");
  lines.push("\n| season | parsed rows | malformed | REG rows | weeks | dup (player,week) | PPR mismatches | worst PPR Δ |");
  lines.push("|---|---|---|---|---|---|---|---|");
  for (const a of audits) {
    lines.push(
      `| ${a.season} | ${a.rows} | ${a.malformed} | ${a.regRows} | ${a.weeks} | ${a.duplicates} | ` +
        `${a.pprMismatches} | ${a.worstPprDelta.toFixed(4)} |`
    );
  }

  const totalMalformed = audits.reduce((s, a) => s + a.malformed, 0);
  const totalDup = audits.reduce((s, a) => s + a.duplicates, 0);
  const totalMismatch = audits.reduce((s, a) => s + a.pprMismatches, 0);

  lines.push("\n### Verdicts\n");
  lines.push(
    `- **Parsing:** ${totalMalformed} malformed rows across ${audits.length} seasons. ` +
      (totalMalformed === 0
        ? "Every row's field count matches its header.\n"
        : "**A misaligned row is another row's values under this row's names — investigate before modelling.**\n")
  );
  lines.push(
    `- **Key uniqueness:** ${totalDup} duplicate (player, week) pairs in regular-season rows. ` +
      (totalDup === 0
        ? "Safe to build per-player history without double-counting.\n"
        : "**Duplicates inflate every history feature — deduplicate first.**\n")
  );
  lines.push(
    `- **Outcome column:** ${totalMismatch} of ${totalConsidered} rows where ` +
      "`fantasy_points_ppr` disagrees with an independent recomputation from its own " +
      "components by more than 0.011. " +
      (totalMismatch === 0
        ? "The target column is trustworthy under standard PPR, so the holdout models are scoring the right thing.\n"
        : "**Either the scoring assumption or the column is wrong, and both invalidate every model fitted on it.**\n")
  );

  lines.push("\n### Missingness, per column the models read\n");
  lines.push(`\nOver ${totalConsidered} QB/RB/WR/TE regular-season rows.\n`);
  lines.push("\n| column | empty | share |");
  lines.push("|---|---|---|");
  for (const c of USED_COLUMNS) {
    const n = missing[c] ?? 0;
    lines.push(`| ${c} | ${n} | ${((100 * n) / Math.max(1, totalConsidered)).toFixed(2)}% |`);
  }
  lines.push(
    "\nUsage columns (`target_share`, `air_yards_share`, `wopr`) are empty for players " +
      "with no receiving involvement in a game — a quarterback, or a back who did not " +
      "run a route. That is a real zero rather than a gap, and the holdout builder " +
      "treats it as such per position rather than dropping the row.\n"
  );

  lines.push("\n### Kickers and team defences are NOT in this bundle\n");
  lines.push(
    "\nThis file has no `K` rows and no kicking columns, and team defences are not " +
      "player rows at all — so nothing here can model them. That is a fact about THIS " +
      "BUNDLE and it was once reported as though it were a fact about the data that " +
      "exists, which was wrong: nflverse publishes " +
      "`player_stats_kicking_<season>.csv`, `stats_team_week_<season>.csv` and the final " +
      "scores needed for points allowed. `npm run acquire:kdst` fetches eight seasons of " +
      "all three in 70 KB, and `npm run holdout:kdst` models them. \"Not in the file I " +
      "already had\" is a different claim from \"does not exist\", and only one of them " +
      "was checked.\n"
  );

  lines.push("\n### Position mix\n");
  lines.push("\n| position | rows |");
  lines.push("|---|---|");
  for (const p of POSITIONS) lines.push(`| ${p} | ${posCounts[p] ?? 0} |`);

  // ── 2. Base rates against the shipped thresholds ────────────────────────
  lines.push("\n## 2. Base rates against the shipped thresholds\n");
  lines.push(
    "\nA threshold almost nobody clears — or almost everybody — makes a probability " +
      "model pointless before it is fitted. These are measured on the nflverse rows, " +
      "so they are also a sanity check that the thresholds transfer across seasons.\n"
  );
  lines.push("\n| position | threshold | rows | cleared | base rate |");
  lines.push("|---|---|---|---|---|");
  for (const pos of POSITIONS) {
    let n = 0;
    let hits = 0;
    for (const key of seasonKeys) {
      for (const r of parseCsvRows(bundle[key]!).rows) {
        if (r.season_type !== "REG" || r.position !== pos) continue;
        const pts = num(r.fantasy_points_ppr);
        if (pts === null) continue;
        n += 1;
        if (pts >= WEEKLY_PROB_MODELS[pos].threshold) hits += 1;
      }
    }
    lines.push(
      `| ${pos} | ${WEEKLY_PROB_MODELS[pos].threshold} | ${n} | ${hits} | ` +
        `${((100 * hits) / Math.max(1, n)).toFixed(1)}% |`
    );
  }

  // ── 3. The 2025 weekly snapshot ─────────────────────────────────────────
  const snap = JSON.parse(gunzipSync(readFileSync(WEEKLY_2025)).toString()) as {
    season: string | number;
    rows: Array<Record<string, unknown>>;
  };
  const prosp = snap.rows.filter((r) => r.kind === "prospective");
  const snapSeen = new Set<string>();
  let snapDup = 0;
  for (const r of prosp) {
    const k = `${r.player_id}|${r.week}`;
    if (snapSeen.has(k)) snapDup += 1;
    snapSeen.add(k);
  }
  const weeksIn = [...new Set(prosp.map((r) => Number(r.week)))].sort((a, b) => a - b);

  lines.push("\n## 3. The 2025 weekly snapshot (what the SHIPPED model was fitted on)\n");
  lines.push(`\n- Season: **${snap.season}**`);
  lines.push(`- Prospective rows: **${prosp.length}** of ${snap.rows.length} total`);
  lines.push(`- Weeks: **${weeksIn.length}** (${weeksIn[0]}–${weeksIn[weeksIn.length - 1]})`);
  lines.push(`- Duplicate (player, week): **${snapDup}**`);
  lines.push(
    `- Fields present: ${Object.keys(prosp[0] ?? {}).join(", ")}\n`
  );
  lines.push(
    "\n**This is the constraint that shapes every weekly-model result in this repo.** " +
      "The snapshot carries a projection and an outcome and nothing else — no usage, no " +
      "opponent, no injury designation. The shipped model can only be tested against " +
      "features derivable from those columns, which is why `docs/model-gauntlet.md` " +
      "searched 44 history-derived covariates and found nothing: there was nothing else " +
      "in the file to find.\n"
  );
  lines.push(
    "\nThe nflverse rows audited in section 1 carry the usage columns AND their own " +
      "`fantasy_points_ppr` outcome, so they support a weekly model in their own right — " +
      "and, spanning 2017–2024, they support a **held-out-season** evaluation that the " +
      "single-season 2025 snapshot cannot. That is what " +
      "`scripts/holdout-weekly-gauntlet.ts` does. What they do NOT carry is the " +
      "FantasyPros projection, so they cannot test the shipped model's own predictor — " +
      "a different question from whether usage predicts weekly outcomes at all.\n"
  );

  const clean = totalMalformed === 0 && totalDup === 0 && totalMismatch === 0 && snapDup === 0;
  lines.push("\n## Overall\n");
  lines.push(
    clean
      ? "\n**PASS.** Parsing is complete, keys are unique, and the outcome column " +
          "reproduces from its own components. Models fitted on these rows are fitted on " +
          "what the reports say they are.\n"
      : "\n**ATTENTION.** One or more checks above found a defect. Fix it before quoting " +
          "any model number computed from these rows.\n"
  );

  writeFileSync(OUT, lines.join("\n"));
  console.log(lines.join("\n"));
  console.log(`\nwrote ${OUT}`);
  if (!clean) process.exit(1);
}

main();
