// Season-simulation calibration harness CLI.
//
// Measures the season simulator's playoff/championship calibration two ways:
//   1. SYNTHETIC self-consistency (always runs): are the displayed probabilities
//      honest, unbiased estimates of the simulator's own season frequencies?
//      Reports coverage (Wilson) + reliability (Brier/ECE). This validates
//      internal calibration + Monte-Carlo error — NOT real-world accuracy.
//   2. REAL backtest (optional): if RAE_BACKTEST_FORECASTS points to a JSON file
//      of [{ "prob": <preseason predicted prob>, "outcome": 0|1 }, …] from
//      completed leagues, scores it with the same machinery. Low-power by nature
//      (one data point per league-season) — reported with that caveat.
//
// Usage:
//   npx tsx scripts/brier-season-sim.ts
//   RAE_BACKTEST_FORECASTS=./data/playoff-forecasts-2025.json npx tsx scripts/brier-season-sim.ts
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import {
  runSyntheticCalibration,
  scoreForecasts,
} from "../src/lib/stats/seasonCalibration";
import type { BrierForecast } from "../src/lib/stats/distribution";

// Targets are meaningful for the REAL backtest (accuracy vs reality). For the
// synthetic run the key honesty metrics are ECE ≈ 0 and coverage ≈ level.
const PLAYOFF_BRIER_TARGET = 0.2;
const CHAMP_BRIER_TARGET = 0.1;

function fmt(x: number): string {
  return Number.isFinite(x) ? x.toFixed(4) : "n/a";
}

function loadRealForecasts(): BrierForecast[] | null {
  const path = process.env.RAE_BACKTEST_FORECASTS;
  if (!path) return null;
  if (!existsSync(path)) {
    console.error(`RAE_BACKTEST_FORECASTS set but file not found: ${path}`);
    process.exit(1);
  }
  const raw = JSON.parse(readFileSync(path, "utf8")) as unknown;
  if (!Array.isArray(raw)) throw new Error("forecasts file must be a JSON array");
  return raw.map((r, i) => {
    const o = r as { prob?: unknown; outcome?: unknown };
    if (typeof o.prob !== "number" || (o.outcome !== 0 && o.outcome !== 1)) {
      throw new Error(`forecast[${i}] must be { prob:number, outcome:0|1 }`);
    }
    return { prob: o.prob, outcome: o.outcome };
  });
}

function main(): void {
  console.log("Season-sim calibration harness\n==============================\n");

  // 1. Synthetic self-consistency.
  const syn = runSyntheticCalibration({ count: 40, nPred: 4000, nTruth: 20000, outcomeDraws: 200 });
  console.log("SYNTHETIC self-consistency (internal calibration, NOT real-world accuracy)");
  console.log(`  configs:            ${syn.nConfigs}  (forecasts: ${syn.nForecasts})`);
  console.log(`  coverage @${syn.coverageLevel * 100}%:      ${fmt(syn.coverage)}  (target ≈ ${syn.coverageLevel})`);
  console.log(`  playoff Brier:      ${fmt(syn.playoffBrier)}   ECE: ${fmt(syn.playoffEce)}`);
  console.log(`  championship Brier: ${fmt(syn.championshipBrier)}   ECE: ${fmt(syn.championshipEce)}`);
  console.log("  reliability (forecast → observed):");
  for (const b of syn.reliabilityBins) {
    console.log(`    bin ${b.binCenter.toFixed(2)}  fc=${b.meanForecast.toFixed(3)}  obs=${b.observedFreq.toFixed(3)}  n=${b.n}`);
  }

  // 2. Optional real backtest.
  const real = loadRealForecasts();
  let realSection = "_No real-data backtest run. Set `RAE_BACKTEST_FORECASTS` to a JSON file of completed-season forecasts to populate this section._\n";
  if (real) {
    const s = scoreForecasts(real);
    const playoffPass = s.brier <= PLAYOFF_BRIER_TARGET;
    console.log("\nREAL backtest (low-power: one data point per league-season — interpret with wide CIs)");
    console.log(`  forecasts: ${s.n}`);
    console.log(`  Brier: ${fmt(s.brier)}   ECE: ${fmt(s.ece)}   (playoff target ≤ ${PLAYOFF_BRIER_TARGET}: ${playoffPass ? "PASS" : "FAIL"})`);
    realSection =
      `Forecasts: ${s.n}. Brier ${fmt(s.brier)}, ECE ${fmt(s.ece)}. ` +
      `**Low statistical power** — one independent outcome per league-season; treat as indicative, not conclusive.\n`;
  } else {
    console.log("\nREAL backtest skipped — set RAE_BACKTEST_FORECASTS=path/to/forecasts.json (see docs/season-calibration.md).");
  }

  // Write the results doc.
  const doc = `# Season-Simulation Calibration

_Generated by \`scripts/brier-season-sim.ts\`. Do not edit by hand._

## What this measures

The season simulator (\`src/lib/seasonSim.ts\`) produces playoff/championship
probabilities as genuine simulated frequencies. This harness checks two things:

1. **Synthetic self-consistency** — are the displayed probabilities honest,
   unbiased estimates of the simulator's own season frequencies (coverage), and
   are they calibrated against outcomes drawn from that truth (reliability)?
   This validates internal calibration + Monte-Carlo estimation error. **It does
   not validate against real NFL outcomes.**
2. **Real backtest** (optional) — scores preseason predictions against actual
   completed-season outcomes. Inherently low-power (one independent data point
   per league-season), so results carry wide confidence intervals.

## Synthetic self-consistency results

- Configs: ${syn.nConfigs} (forecasts: ${syn.nForecasts})
- Coverage @ ${syn.coverageLevel * 100}%: **${fmt(syn.coverage)}** (target ≈ ${syn.coverageLevel})
- Playoff Brier **${fmt(syn.playoffBrier)}**, ECE **${fmt(syn.playoffEce)}**
- Championship Brier **${fmt(syn.championshipBrier)}**, ECE **${fmt(syn.championshipEce)}**

A near-${syn.coverageLevel} coverage and near-zero ECE confirm the displayed
probabilities mean what they say (they match realized simulation frequencies
within Monte-Carlo error). They do **not** certify real-world accuracy.

## Real-data backtest

${realSection}
To run one, build a JSON array of \`{ "prob": <preseason predicted playoff prob>,
"outcome": 0|1 }\` from completed Sleeper leagues and point
\`RAE_BACKTEST_FORECASTS\` at it. The production targets (playoff Brier ≤
${PLAYOFF_BRIER_TARGET}, championship Brier ≤ ${CHAMP_BRIER_TARGET}) apply to
this real backtest, not the synthetic self-consistency run.
`;
  writeFileSync("docs/season-calibration.md", doc);
  console.log("\nWrote docs/season-calibration.md");
}

main();
